### ISSUE TITLE
2d variant?

### ISSUE THREAD

**Issue by mreinstein** [kevzettler/gl-swept-sphere-triangle#8]
Thanks for porting this to modern gl-matrix compatibility! 

I'm wondering if this code be simplified to handle the 2d case (swept circle vs line segment.)
It seems like the logic would remain the same, except:

* checking only 2 vertexes instead of 3
* using vec2 instead of vec3 everywhere
* eliminating 2 of the edge tests
* replace `pointInTriangle` with `pointInSegment`

thoughts?

**Comment by kevzettler** [comment]
Hi @mreinstein that approach sounds plausible to me. I haven't thought deeply about it and don't have a need for the 2d case. Let me know if that works out for you.

**Comment by mreinstein** [comment]
actually, I got this working in a local build. Seems to work great! 

Maybe the best thing to do is cross link each other's projects... (e.g., "this library is for 2d sphere sweeps. If you're looking for a 3d sphere-triangle routine, check out kevzettler/gl-swept-sphere-triangle")

**Comment by kevzettler** [comment]
@mreinstein great work. Yes I think separate modules is a good idea. Do add your package to the stack.gl package list at:

https://github.com/stackgl/packages/wiki/Packages

if it is beneficial to the ecosystem.



Also please let me know if you see any optimizations in the underlying code that could benefit this module as well

**Comment by mreinstein** [comment]
>  let me know if you see any optimizations in the underlying code that could benefit this module as well

I think the underlying code is _mostly_ reasonable peformance wise. The 2 biggest areas where I think there could be improvement are:
* using a broadphase culling step to reduce the initial set of triangles (probably out of scope for this module though)
* converting to wasm would be amazing. There is a lot of math that I'd think would benefit from using lower level instructions (I have no idea if this is feasible though)

I'd say the biggest missing thing is converting to ellipsoid space (so a vec2 or vec3 radius.)
I'm probably going to work on this in the 2d case and maybe I'll send a PR to this module, assuming that's not already a work in progress for you.
